"""init

Revision ID: b5ece89bb9f7
Revises: 
Create Date: 2026-04-29 19:48:10.928601

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ece89bb9f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('role_slug', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('token_fingerprint', sa.String(length=16), nullable=True),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_role_slug'), 'agent_events', ['role_slug'], unique=False)
    op.create_index(op.f('ix_agent_events_ts'), 'agent_events', ['ts'], unique=False)
    op.create_table('provision_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('role_slug', sa.String(length=128), nullable=False),
    sa.Column('role_version', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=128), nullable=True),
    sa.Column('agent_id_returned', sa.String(length=64), nullable=True),
    sa.Column('caller_token_fingerprint', sa.String(length=16), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('integration_bindings', sa.JSON(), nullable=False),
    sa.Column('extra_skills', sa.JSON(), nullable=False),
    sa.Column('extra_subagents', sa.JSON(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provision_events_organization_id'), 'provision_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_provision_events_role_slug'), 'provision_events', ['role_slug'], unique=False)
    op.create_index(op.f('ix_provision_events_ts'), 'provision_events', ['ts'], unique=False)
    op.create_table('role_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_slug'), 'role_templates', ['slug'], unique=True)
    op.create_table('role_template_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_template_id', 'version', name='uq_role_template_versions_role_version')
    )
    op.create_index(op.f('ix_role_template_versions_manifest_sha256'), 'role_template_versions', ['manifest_sha256'], unique=False)
    op.create_index(op.f('ix_role_template_versions_role_template_id'), 'role_template_versions', ['role_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_template_versions_role_template_id'), table_name='role_template_versions')
    op.drop_index(op.f('ix_role_template_versions_manifest_sha256'), table_name='role_template_versions')
    op.drop_table('role_template_versions')
    op.drop_index(op.f('ix_role_templates_slug'), table_name='role_templates')
    op.drop_table('role_templates')
    op.drop_index(op.f('ix_provision_events_ts'), table_name='provision_events')
    op.drop_index(op.f('ix_provision_events_role_slug'), table_name='provision_events')
    op.drop_index(op.f('ix_provision_events_organization_id'), table_name='provision_events')
    op.drop_table('provision_events')
    op.drop_index(op.f('ix_agent_events_ts'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_role_slug'), table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
